export default {
    // BASE
    TOGGLE_CATEGORIES_MENU: Symbol('TOGGLE_CATEGORIES_MENU'),
    SET_PAGE_NAME: Symbol('SET_PAGE_NAME'),
    SET_DEVICE_PARAMS: Symbol('SET_DEVICE_PARAMS'),
    SOMETHING_WENT_WRONG: Symbol('SOMETHING_WENT_WRONG'),
    SET_ASIDE_MENU_CLOSEST: Symbol('SET_ASIDE_MENU_CLOSEST'),
    ADD_TOAST: Symbol('ADD_TOAST'),
    REMOVE_TOAST: Symbol('REMOVE_TOAST'),
    SET_HEADER_RECT: Symbol('SET_HEADER_RECT'),

    // HOME
    GET_POPULAR_CATEGORIES: Symbol('GET_POPULAR_CATEGORIES'),
    GET_SUGGESTED_DATA: Symbol('GET_SUGGESTED_DATA'),

    // FILTERS
    SET_SELECTED_FILTER: Symbol('SET_SELECTED_FILTER'),
    SET_LOCATIONS: Symbol('SET_LOCATIONS'),
    SET_POSSIBILITIES: Symbol('SET_POSSIBILITIES'),
    SET_WITH_PICTURES_RESULTS: Symbol('SET_WITH_PICTURES_RESULTS'),
    SET_APPEARANCE: Symbol('SET_APPEARANCE'),
    SET_PRICE: Symbol('SET_PRICE'),
    SET_AVAILABILITY: Symbol('SET_AVAILABILITY'),
    SET_SPEAK_LANGUAGES: Symbol('SET_SPEAK_LANGUAGES'),
    SET_MEETING_PLACES: Symbol('SET_MEETING_PLACES'),
    RESET_SELECTED_FILTER: Symbol('RESET_SELECTED_FILTER'),

    // ADS
    SET_MY_ADS: Symbol('SET_MY_ADS'),
    TOGGLE_SELECTED_AD: Symbol('TOGGLE_SELECTED_AD'),
};