export default {
    build: [
        {title: 'Normal', value: 'normal', count: 100},
        {title: 'Athletic', value: 'athletic', count: 100},
        {title: 'Slim', value: 'slim', count: 100},
        {title: 'Chubby', value: 'chubby', count: 100},
        {title: 'Fat', value: 'fat', count: 100},
    ], hair_color: [
        {title: 'Blonde', value: 'blonde', count: 100},
        {title: 'Brown', value: 'brown', count: 100},
        {title: 'Black', value: 'black', count: 100},
        {title: 'Red', value: 'red', count: 100},
        {title: 'Gray', value: 'gray', count: 100},
        {title: 'None', value: 'none', count: 100},
        {title: 'Other', value: 'other', count: 100},
    ], cup: [
        {title: 'A', value: 'a', count: 100},
        {title: 'AA', value: 'aa', count: 100},
        {title: 'B', value: 'b', count: 100},
        {title: 'C', value: 'c', count: 100},
        {title: 'D', value: 'd', count: 100},
        {title: 'DD', value: 'dd', count: 100},
        {title: 'E', value: 'e', count: 100},
        {title: 'F', value: 'f', count: 100},
        {title: 'G', value: 'g', count: 100},
    ], nationality: [
        {title: 'Morocco', value: 'morocco', count: 100},
        {title: 'Belgium', value: 'belgium', count: 100},
        {title: 'France', value: 'france', count: 100},
        {title: 'Turkey', value: 'turkey', count: 100},
        {title: 'Austria', value: 'austria', count: 100},
        {title: 'Poland', value: 'poland', count: 100},
        {title: 'Czechia', value: 'czechia', count: 100},
        {title: 'Slovakia', value: 'slovakia', count: 100},
        {title: 'German', value: 'german', count: 100},
        {title: 'Romania', value: 'romania', count: 100},
        {title: 'Ukraine', value: 'ukraine', count: 100},
        {title: 'Belarus', value: 'belarus', count: 100},
        {title: 'Spain', value: 'spain', count: 100},
        {title: 'Italy', value: 'italy', count: 100},
        {title: 'Greece', value: 'greece', count: 100},
        {title: 'Bulgaria', value: 'bulgaria', count: 100},
        {title: 'Hungary', value: 'hungary', count: 100},
        {title: 'Netherlands', value: 'netherlands', count: 100},
    ],
}