export default [
    {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Apr 07 2021 18:06:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['cta'],
        isSeen: true,
        id: 1,
    }, {
        type: 'sub-item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2020 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatar.png',
        btns: [],
        isSeen: false,
        id: 2,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['decline', 'accept'],
        isSeen: true,
        id: 3,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '',
        btns: ['decline', 'accept'],
        isSeen: false,
        id: 4,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['cta'],
        isSeen: true,
        id: 5,
    }, {
        type: 'sub-item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: [],
        isSeen: true,
        id: 6,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['decline', 'accept'],
        isSeen: true,
        id: 7,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '',
        btns: ['decline', 'accept'],
        isSeen: false,
        id: 8,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['cta'],
        isSeen: true,
        id: 9,
    }, {
        type: 'sub-item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: [],
        isSeen: false,
        id: 10,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '/images/avatarPath.jpg',
        btns: ['decline', 'accept'],
        isSeen: true,
        id: 11,
    }, {
        type: 'item',
        label: 'Label of Item',
        explainer_text: '',
        mail_settings: '',
        notification_settings: '',
        connected_item: '',
        date: 'Fri Jan 29 2021 16:26:37 GMT+0400 (Armenia Standard Time)',
        email_subject: '',
        notification_text: 'Epicurus in bonis sit voluptatem ipsam per se ipsam causam ista, quae dices. voluptatem',
        image: '',
        btns: ['decline', 'accept'],
        isSeen: false,
        id: 12,
    },
]